/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarouselNotice: typeof import('./src/components/CarouselNotice.vue')['default']
    LoadingMask: typeof import('./src/components/LoadingMask.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscribeInfoCard: typeof import('./src/components/SubscribeInfoCard.vue')['default']
    SubscribeLinkCard: typeof import('./src/components/SubscribeLinkCard.vue')['default']
    WelcomeCard: typeof import('./src/components/WelcomeCard.vue')['default']
  }
}
